name: Tests
on: [pull_request]


jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mxcl/xcodebuild@v1
        with:
          scheme: Bitski-iOS-SDK
          sdk: iphonesimulator
          platform: iOS
          code-coverage: true
          destination: 'platform=iOS Simulator,name=iPhone 13'
